export const preloadTooltip = [
  "/fontSize-poster-blured.jpg",
  "/fontType-poster-blured.jpg",
  "/lineSpacing-poster-blured.jpg",
  "/marginTop-poster-blured.jpg",
  "/marginRight-poster-blured.jpg",
  "/marginBottom-poster-blured.jpg",
  "/marginLeft-poster-blured.jpg",
  "/firstLineIndent-poster-blured.jpg",
  "/justifyContent-poster-blured.jpg",
  "/heading1JustifyContent-poster-blured.jpg",
  "/heading1FirstLineIndent-poster-blured.jpg",
  "/heading1Capitalize-poster-blured.jpg",
  "/heading1Bold-poster-blured.jpg",
];
