export const templates = [
  {
    id: "one-heading",
    title: "First paragraph settings",
    headingCount: 1,
    paragraphIndex: 0,

    jcLabel: "Justify content",
    jcRatio: "490/360",
    jcTooltip: "Justify first paragraph left, center, right or both",
    jcPoster: "/heading1JustifyContent-poster-blured.jpg",
    jcVideo: "/heading1JustifyContent.mp4",

    fLindLabel: "First line indent",
    fLindRatio: "490/260",
    fLindTooltip: "Indent the first line of the first paragraph",
    fLindPoster: "/heading1FirstLineIndent-poster-blured.jpg",
    fLindVideo: "/heading1FirstLineIndent.mp4",

    capLabel: "Uppercase",
    capRatio: "490/400",
    capTooltip: "Set uppercase for the first paragraph",
    capPoster: "/heading1Capitalize-poster-blured.jpg",
    capVideo: "/heading1Capitalize.mp4",

    boldLabel: "Bold",
    boldRatio: "490/360",
    boldTooltip: "Set the first paragraph bold",
    boldPoster: "/heading1Bold-poster-blured.jpg",
    boldVideo: "/heading1Bold.mp4",
  },
  {
    id: "two-headings",
    title: "Second paragraph settings",
    headingCount: 2,
    paragraphIndex: 1,

    jcLabel: "Justify content",
    jcRatio: "420/390",
    jcTooltip: "Justify second paragraph left, center, right or both",
    jcPoster: "/heading2JustifyContent-poster-blured.jpg",
    jcVideo: "/heading2JustifyContent.mp4",

    fLindLabel: "First line indent",
    fLindRatio: "420/390",
    fLindTooltip: "Indent the first line of the second paragraph",
    fLindPoster: "/heading2FirstLineIndent-poster-blured.jpg",
    fLindVideo: "/heading2FirstLineIndent.mp4",

    capLabel: "Uppercase",
    capRatio: "420/440",
    capTooltip: "Set uppercase for the second paragraph",
    capPoster: "/heading2Capitalize-poster-blured.jpg",
    capVideo: "/heading2Capitalize.mp4",

    boldLabel: "Bold",
    boldRatio: "480/360",
    boldTooltip: "Set the second paragraph bold",
    boldPoster: "/heading2Bold-poster-blured.jpg",
    boldVideo: "/heading2Bold.mp4",
  },
  {
    id: "three-headings",
    title: "Third paragraph settings",
    headingCount: 3,
    paragraphIndex: 2,

    jcLabel: "Justify content",
    jcRatio: "420/410",
    jcTooltip: "Justify third paragraph left, center, right or both",
    jcPoster: "/heading3JustifyContent-poster-blured.jpg",
    jcVideo: "/heading3JustifyContent.mp4",

    fLindLabel: "First line indent",
    fLindRatio: "420/350",
    fLindTooltip: "Indent the first line of the third paragraph",
    fLindPoster: "/heading3FirstLineIndent-poster-blured.jpg",
    fLindVideo: "/heading3FirstLineIndent.mp4",

    capLabel: "Uppercase",
    capRatio: "500/460",
    capTooltip: "Set uppercase for the third paragraph",
    capPoster: "/heading3Capitalize-poster-blured.jpg",
    capVideo: "/heading3Capitalize.mp4",

    boldLabel: "Bold",
    boldRatio: "480/400",
    boldTooltip: "Set the third paragraph bold",
    boldPoster: "/heading3Bold-poster-blured.jpg",
    boldVideo: "/heading3Bold.mp4",
  },
  {
    id: "four-headings",
    title: "Forth paragraph settings",
    headingCount: 4,
    paragraphIndex: 3,

    jcLabel: "Justify content",
    jcRatio: "420/440",
    jcTooltip: "Justify forth paragraph left, center, right or both",
    jcPoster: "/heading4JustifyContent-poster-blured.jpg",
    jcVideo: "/heading4JustifyContent.mp4",

    fLindLabel: "First line indent",
    fLindRatio: "420/380",
    fLindTooltip: "Indent the first line of the forth paragraph",
    fLindPoster: "/heading4FirstLineIndent-poster-blured.jpg",
    fLindVideo: "/heading4FirstLineIndent.mp4",

    capLabel: "Uppercase",
    capRatio: "480/490",
    capTooltip: "Set uppercase for the forth paragraph",
    capPoster: "/heading4Capitalize-poster-blured.jpg",
    capVideo: "/heading4Capitalize.mp4",

    boldLabel: "Bold",
    boldRatio: "480/440",
    boldTooltip: "Set the forth paragraph bold",
    boldPoster: "/heading4Bold-poster-blured.jpg",
    boldVideo: "/heading4Bold.mp4",
  },
];
