export const templates = [
  {
    id: "one-heading",
    title: "First paragraph settings",
    headingCount: 1,
    paragraphIndex: 0,
    jcPoster: "/heading1JustifyContent-poster-blured.jpg",
    jcVideo: "/heading1JustifyContent.mp4",
    fLiPoster: "/heading1FirstLineIndent-poster-blured.jpg",
    fLiVideo: "/heading1FirstLineIndent.mp4",
    capPoster: "/heading1Capitalize-poster-blured.jpg",
    capVideo: "/heading1Capitalize.mp4",
    boldPoster: "/heading1Bold-poster-blured.jpg",
    boldVideo: "/heading1Bold.mp4",
  },
  {
    id: "two-headings",
    title: "Second paragraph settings",
    headingCount: 2,
    paragraphIndex: 1,
    jcPoster: "/heading2JustifyContent-poster-blured.jpg",
    jcVideo: "/heading2JustifyContent.mp4",
    fLiPoster: "/heading2FirstLineIndent-poster-blured.jpg",
    fLiVideo: "/heading2FirstLineIndent.mp4",
    capPoster: "/heading2Capitalize-poster-blured.jpg",
    capVideo: "/heading2Capitalize.mp4",
    boldPoster: "/heading2Bold-poster-blured.jpg",
    boldVideo: "/heading2Bold.mp4",
  },
  {
    id: "three-headings",
    title: "Third paragraph settings",
    headingCount: 3,
    paragraphIndex: 2,
    jcPoster: "/heading3JustifyContent-poster-blured.jpg",
    jcVideo: "/heading3JustifyContent.mp4",
    fLiPoster: "/heading3FirstLineIndent-poster-blured.jpg",
    fLiVideo: "/heading3FirstLineIndent.mp4",
    capPoster: "/heading3Capitalize-poster-blured.jpg",
    capVideo: "/heading3Capitalize.mp4",
    boldPoster: "/heading3Bold-poster-blured.jpg",
    boldVideo: "/heading3Bold.mp4",
  },
  {
    id: "four-headings",
    title: "Forth paragraph settings",
    headingCount: 4,
    paragraphIndex: 3,
    jcPoster: "/heading4JustifyContent-poster-blured.jpg",
    jcVideo: "/heading4JustifyContent.mp4",
    fLiPoster: "/heading4FirstLineIndent-poster-blured.jpg",
    fLiVideo: "/heading4FirstLineIndent.mp4",
    capPoster: "/heading4Capitalize-poster-blured.jpg",
    capVideo: "/heading4Capitalize.mp4",
    boldPoster: "/heading4Bold-poster-blured.jpg",
    boldVideo: "/heading4Bold.mp4",
  },
];
